receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889" # 프로메테우스가 스크랩할 엔드포인트

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus] # 메트릭을 debug와 prometheus로 전송
    logs:
      receivers: [otlp]
      exporters: [debug]
